name: Build and Test NODE
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Force HTTPS for Git dependencies
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn generate-plugin-schema
      - run: yarn test:ci
